package it.mattiacaddeo.MyEXE_Airport.enums;

public enum StatusLogging {
	LOGIN_SUCCESFULLY
	, LOGGED_OUT
	, ALREADY_LOGGED_ON
	, ALREADY_LOGGED_OFF
	, WRONG_PASSWORD
	, WRONG_MAIL
	, WRONG_ID_CLIENT
	, WRONG_ROLE
	, NOT_SIGNED_UP
}
